import './globals.css'
import { Comic_Neue, Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const comicNeue = Comic_Neue({  weight: '700', subsets: ['latin'] })

export const metadata = {
  title: 'Local Shops',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={comicNeue.className}>{children}</body>
    </html>
  )
}
