import './globals.css'
import 'material-icons/iconfont/material-icons.css'
import { Titillium_Web } from 'next/font/google'

import HeaderSearch from '@/components/HeaderSearch'

const titilliumWeb = Titillium_Web({ weight:'300', subsets: ['latin'] })

export const metadata = {
  title: 'Local Shops',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={titilliumWeb.className}>
        <HeaderSearch/>
        {children}
      </body>
    </html>
  )
}